### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by Clara-0103** [mj-sam/BCI_HW#1]
excuse me? can i take the liberty to ask if the MyCSP mentioned in the program can be uploaded? thank you very much.

**Comment by mj-sam** [comment]
Hi Clara
I have added the MyCSP file to the HW3 folder. Let me know if you have further question.

**Comment by Clara-0103** [comment]
> Hi Clara I have added the MyCSP file to the HW3 folder. Let me know if you have further question.
you are nice! thanks for your sharing.
